version: "3.9"

services:
  database:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: chandresh
      POSTGRES_PASSWORD: chandresh_123
      POSTGRES_DB: bank-simulation
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-app
    restart: always
    ports:
      - "3333:3333"
    depends_on:
      - database
    environment:
      DATABASE_URL: postgres://chandresh:chandresh_123@database:5432/bank-simulation

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-app
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  postgres_data:
